version: 2

jobs:
  checkout:
    docker:
      - image: circleci/node:lts-buster
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-gb-studio-src-{{ .Branch }}-{{ .Revision }}
            - v1-gb-studio-src-{{ .Branch }}-
            - v1-gb-studio-src-
      - checkout
      - save_cache:
          paths:
            - ./*
          key: v1-gb-studio-src-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-gb-studio-dependencies-{{ checksum "yarn.lock" }}
            - v1-gb-studio-dependencies-
      - run: yarn --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v1-gb-studio-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  test:
    docker:
      - image: circleci/node:lts-buster
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test

  "make:mac":
    docker:
      - image: circleci/node:lts-buster
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - checkout
      - run: sudo yarn make:mac
      - run: sudo mv ~/repo/out/make/zip/darwin/x64/*.zip ~/repo/out/make/gb-studio-${CIRCLE_BRANCH}-darwin_x86_64.zip
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/out/make

  "make:win32":
    docker:
      - image: circleci/node:lts-buster
    working_directory: ~/repo
    steps:
      - run: sudo dpkg --add-architecture i386
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install wine
      - run: sudo apt-get -y install wine32
      - run: sudo apt-get -y install mono-devel
      - attach_workspace:
          at: ~/
      - checkout
      - run: sudo yarn make:win32
      - run: sudo mv ~/repo/out/make/zip/win32/ia32/*.zip ~/repo/out/make/gb-studio-${CIRCLE_BRANCH}-windows_x86.zip
      - run: sudo mv ~/repo/out/make/squirrel.windows/ia32 ~/repo/out/make/gb-studio-${CIRCLE_BRANCH}-windows_x86-squirrel
      - run:
          name: zip squirrel build
          command: sudo zip gb-studio-${CIRCLE_BRANCH}-windows_x86-squirrel.zip ./gb-studio-${CIRCLE_BRANCH}-windows_x86-squirrel/*
          working_directory: ~/repo/out/make
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/out/make

  "make:win64":
    docker:
      - image: circleci/node:lts-buster
    working_directory: ~/repo
    steps:
      - run: sudo dpkg --add-architecture i386
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install wine
      - run: sudo apt-get -y install wine32
      - run: sudo apt-get -y install mono-devel
      - attach_workspace:
          at: ~/
      - checkout
      - run: sudo yarn make:win
      - run: sudo mv ~/repo/out/make/zip/win32/x64/*.zip ~/repo/out/make/gb-studio-${CIRCLE_BRANCH}-windows_x86_64.zip
      - run: sudo mv ~/repo/out/make/squirrel.windows/x64 ~/repo/out/make/gb-studio-${CIRCLE_BRANCH}-windows_x86_64-squirrel
      - run:
          name: zip squirrel build
          command: sudo zip gb-studio-${CIRCLE_BRANCH}-windows_x86_64-squirrel.zip ./gb-studio-${CIRCLE_BRANCH}-windows_x86_64-squirrel/*
          working_directory: ~/repo/out/make
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/out/make

  "make:linux":
    docker:
      - image: circleci/node:lts-buster
    working_directory: ~/repo
    steps:
      - run: sudo apt-get -y install fakeroot
      - run: sudo apt-get -y install rpm
      - attach_workspace:
          at: ~/
      - checkout
      - run: sudo yarn make:linux
      - run: sudo mv ~/repo/out/make/deb/x64/*.deb ~/repo/out/make/gb-studio-${CIRCLE_BRANCH}-linux_x86_64.deb
      - run: sudo mv ~/repo/out/make/rpm/x64/*.rpm ~/repo/out/make/gb-studio-${CIRCLE_BRANCH}-linux_x86_64.rpm
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/out/make

  upload_artifacts:
    docker:
      - image: circleci/node:lts-buster
    working_working_directory: /
    steps:
      - attach_workspace:
          at: ~/
      - store_artifacts:
          path: ~/repo/out/make
          destination: builds

workflows:
  version: 2
  deployment:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - "make:mac":
          requires:
            - checkout
          filters:
            branches:
              only:
                - develop
                - master
                - main
                - v3alpha
                - v2beta
                - uge-tracker
      - "make:win32":
          requires:
            - checkout
          filters:
            branches:
              only:
                - develop
                - master
                - main
                - v3alpha
                - v2beta
                - uge-tracker
      - "make:win64":
          requires:
            - checkout
          filters:
            branches:
              only:
                - develop
                - master
                - main
                - v3alpha
                - v2beta
                - uge-tracker
      - "make:linux":
          requires:
            - checkout
          filters:
            branches:
              only:
                - develop
                - master
                - main
                - v3alpha
                - v2beta
                - uge-tracker
      - "upload_artifacts":
          requires:
            - "make:mac"
            - "make:win32"
            - "make:win64"
            - "make:linux"
          filters:
            branches:
              only:
                - develop
                - master
                - main
                - v3alpha
                - v2beta
                - uge-tracker
